version: "3.8"
services:

  # base images
  flask_service:
    build:
      context: ../shared/flask
    image: flask_service:python-3.10-slim-bullseye
    restart: "no"
    deploy:
      replicas: 0

  # front-proxy
  front-envoy:
    image: envoyproxy/envoy-dev:latest
    volumes:
    - ./service-envoy.yaml:/etc/service-envoy.yaml
    - ./front-envoy.yaml:/etc/front-envoy.yaml
    command: -c etc/front-envoy.yaml --service-cluster front-proxy
    ports:
    - "${PORT_PROXY:-8080}:8080"
    - "${PORT_HTTPS:-8443}:8443"
    - "${PORT_STATS:-8001}:8001"

  service1:
    image: gcr.io/tetratelabs/color-app:1.0.0
    environment:
      - BG_COLOR=blue
    volumes:
    - ./service-envoy.yaml:/etc/service-envoy.yaml

  service2:
    image: gcr.io/tetratelabs/color-app:1.0.0
    environment:
      - BG_COLOR=green
    volumes:
    - ./service-envoy.yaml:/etc/service-envoy.yaml