services:
  blue:
    container_name: blue
    image: gcr.io/tetratelabs/color-app:1.0.0
    environment:
      - BG_COLOR=blue
  green:
    container_name: green
    image: gcr.io/tetratelabs/color-app:1.0.0
    environment:
      - BG_COLOR=green
  envoy:
    container_name: daniel_envoy
    image: envoyproxy/envoy:v1.24.0
    command: --config-path /usr/src/app/envoy-demo.yaml
    volumes:
      - "./:/usr/src/app"
    restart: always
    ports:
      - "10000:10000"
      - "8001:8001"